// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOYhVnrRivVxFLLm7ZX89zxD4hnvz7CQo',
    appId: '1:351946278341:web:db6dba3eb8c52075c977ac',
    messagingSenderId: '351946278341',
    projectId: 'thread-clone-toywater',
    authDomain: 'thread-clone-toywater.firebaseapp.com',
    storageBucket: 'thread-clone-toywater.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXDW90uyJqSMYITxnocdsN4o9t2rGtGsw',
    appId: '1:351946278341:android:6fd90e0e8e51152bc977ac',
    messagingSenderId: '351946278341',
    projectId: 'thread-clone-toywater',
    storageBucket: 'thread-clone-toywater.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtv3sNTXUsdCCcaUiFi3i-OaWri9y602Q',
    appId: '1:351946278341:ios:223826b05ee6a9d7c977ac',
    messagingSenderId: '351946278341',
    projectId: 'thread-clone-toywater',
    storageBucket: 'thread-clone-toywater.firebasestorage.app',
    iosBundleId: 'com.example.navigationTimeChallenge12',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOYhVnrRivVxFLLm7ZX89zxD4hnvz7CQo',
    appId: '1:351946278341:web:d776ed1574902a2ec977ac',
    messagingSenderId: '351946278341',
    projectId: 'thread-clone-toywater',
    authDomain: 'thread-clone-toywater.firebaseapp.com',
    storageBucket: 'thread-clone-toywater.firebasestorage.app',
  );

}